# Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit.

comptime U4 = SIMD[DType.uint32, 4]

comptime K: UInt32 = 32
comptime KEY = U4(0x00000001, 0x00000002, 0x00000003, 0x00000004)

def t_o() -> List[U4]:
    return [U4(0x00000001, 0x00000002, 0x00000003, 0x00000004), U4(0x00000000, 0x00000000, 0x00000000, 0x00000000)]

def t_h() -> List[U4]:
    return [U4(0x00000005, 0x00000006, 0x00000007, 0x00000008), U4(0x00000000, 0x00000000, 0x00000000, 0x00000000)]

def t_o_out() -> List[U4]:
    return [U4(0x00000017, 0x00150007, 0x00000001, 0x00050008), U4(0x00000000, 0x00000000, 0x00000000, 0x00000000)]

def t_h_out() -> List[U4]:
    return [U4(0x9e377ca9, 0x0000e006, 0x02000007, 0x00001820), U4(0x9e3779b9, 0x00000000, 0x00000000, 0x00000000)]

def f_counter() -> List[UInt64]:
    return [0, 1]

def f_o() -> List[U4]:
    return [U4(0x472bef12, 0xc0977c66, 0xd330ac3a, 0xb11a020d), U4(0xb777c10c, 0x2f6b5a5d, 0x67a9ce03, 0x7de06a50)]

def f_h() -> List[U4]:
    return [U4(0xbfa0b6ba, 0xecdbc48e, 0xf1989116, 0xc2374d96), U4(0xd0c2dc4f, 0xe1e50e0f, 0x89efc72c, 0x6e82b062)]

def stream_first_word() -> List[Int]:
    return [0, 4, 32]

def stream_words() -> List[U4]:
    return [U4(0x0a5bcb90, 0x6dfe98bc, 0x9612198a, 0xac115fd8), U4(0x33f598d7, 0xb5c280ca, 0x7a8e7b99, 0x8c362290), U4(0x9da7bac0, 0x4aca79eb, 0xbeb1f65a, 0xe2f0d5a1)]

def float64_index() -> List[Int]:
    return [0, 16]

def float64_value() -> List[Float64]:
    return [0.4296660861094629, 0.2921520424112306]

def float32_index() -> List[Int]:
    return [2]

def float32_value() -> List[Float32]:
    return [0.58621365]

def bool_index() -> List[Int]:
    return [0, 1, 2, 3, 4, 5, 6, 7, 128]

def bool_value() -> List[Bool]:
    return [False, False, False, False, True, False, False, True, True]

comptime SPLIT0 = U4(0xe256e9a1, 0x5020f806, 0x3bd3f7dc, 0x5328763d)
comptime SPLIT1 = U4(0xa9ea3f0b, 0x47f97af0, 0xd1844c53, 0x97e9cee2)
comptime FORK0 = U4(0x67fd37c5, 0x9dc0b8c6, 0x4e3bd55e, 0xaf3f2216)
comptime PURPOSE7 = U4(0x8048398f, 0x1678e814, 0xd8823983, 0xc4b1045c)

comptime SEED: UInt128 = 42
comptime SEED_KEY = U4(0x421d21eb, 0x32d31777, 0x62e7564b, 0xdf2bdf82)

def seed_f64_index() -> List[Int]:
    return [0, 2, 16]

def seed_f64_value() -> List[Float64]:
    return [0.9829130398628935, 0.47759300283385586, 0.9692135305890753]

def seed_u32_index() -> List[Int]:
    return [0]

def seed_u32_value() -> List[UInt32]:
    return [0x05e80cec]
