#!/usr/bin/env python3
"""Write zig_tables.mojo, the Float64 normal ziggurat tables, from the spec's table file.

    python3 tools/gen_zig_tables.py ../tandem-spec/tables/normal_f64_zig1024.json > zig_tables.mojo

The file's SHA-256 must match the value the spec publishes, so a changed table file fails here
instead of changing the normals. Each Float64 is written as its bit pattern.
"""
import hashlib
import json
import struct
import sys

SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"
LAYERS = 1024


def bits(s):
    x = float.fromhex(s)
    if x.hex() != s:
        raise SystemExit(f"not a canonical hexadecimal float: {s}")
    return f"0x{struct.unpack('<Q', struct.pack('<d', x))[0]:016X}"


def table(name, values):
    rows = ",\n".join("    " + ", ".join(values[i : i + 4]) for i in range(0, len(values), 4))
    return f"comptime {name} = StaticTuple[UInt64, {len(values)}](\n{rows},\n)\n"


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    data = open(sys.argv[1], "rb").read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SHA256:
        raise SystemExit(f"{sys.argv[1]}: SHA-256 {digest}, expected {SHA256}")
    t = json.loads(data)
    if t["layers"] != LAYERS or len(t["W"]) != LAYERS or len(t["K"]) != LAYERS or len(t["Y"]) != LAYERS + 1:
        raise SystemExit("unexpected table sizes")
    w = [bits(s) for s in t["W"]]
    neg = [bits("-" + s) for s in t["W"]]
    print(f"""# Generated by tools/gen_zig_tables.py from the spec's tables/normal_f64_zig1024.json
# (SHA-256 {SHA256}). Do not edit.
# The Float64 normal ziggurat of Appendix A with {LAYERS} layers, each Float64 as its bits. ZIG_W
# holds the widths W[i] for a clear sign bit and -W[i] at {LAYERS} + i for a set one, so the
# index is the low 11 bits of a draw.
from std.utils import StaticTuple

comptime ZIG_R_BITS: UInt64 = {bits(t["R"])}
""")
    print(table("ZIG_W", w + neg))
    print(table("ZIG_K", [str(int(v)) for v in t["K"]]))
    print(table("ZIG_Y", [bits(s) for s in t["Y"]]).rstrip("\n"))


if __name__ == "__main__":
    main()
