#!/usr/bin/env python3
"""Mojo fixtures for tests/test_derived.mojo from tandem-c's cross-check headers, which tandem-c
generates from the shared device core (tandem-cuda core.hpp).

    python3 tools/gen_derived.py ../tandem-c/tests > tests/derived_data.mojo
"""
import re
import sys

tests = sys.argv[1]


def read(name):
    with open(f"{tests}/{name}") as f:
        return f.read()


def cases(text, array):
    # Entries are `{n, {values}, end_pos}`.
    body = re.search(rf"{array}\[\] = \{{(.*?)\n\}};", text, re.S).group(1)
    out = []
    for n, vals, end in re.findall(r"\{(\d+)u(?:ll)?,\s*\{([^}]*)\},\s*(\d+)u\}", body):
        out.append((int(n), [int(v.strip().rstrip("ul")) for v in vals.split(",")], int(end)))
    return out


def ints(name, ty, values):
    return f"def {name}() -> List[{ty}]:\n    return [{', '.join(str(v) for v in values)}]\n"


def reals(name, ty, text, array):
    body = re.search(rf"{array}\[[^\]]*\] = \{{(.*?)\}};", text, re.S).group(1)
    values = [v.strip().rstrip("f") for v in body.split(",") if v.strip()]
    return f"def {name}() -> List[{ty}]:\n    return [{', '.join(values)}]\n"


below = read("cross_below.h")
fill = read("cross_fill_below.h")
normal = read("cross_normal.h")

out = ["# Generated by tools/gen_derived.py from tandem-c's cross-check headers. Do not edit.",
       "# Each case starts from `Tandem(42)` after one `next_bool`. The values of case i are",
       "# elements 64 * i to 64 * i + 63 of the `want` list.\n"]
for label, text, name32, name64 in [("below", below, "CROSS_U32", "CROSS_U64"), ("fill_below", fill, "CROSS_FILL_U32", "CROSS_FILL_U64")]:
    for bits, array in [(32, name32), (64, name64)]:
        cs = cases(text, array)
        assert all(len(v) == 64 for _, v, _ in cs)
        out.append(ints(f"{label}_u{bits}_bounds", f"UInt{bits}", [n for n, _, _ in cs]))
        out.append(ints(f"{label}_u{bits}_want", f"UInt{bits}", [x for _, v, _ in cs for x in v]))
        out.append(ints(f"{label}_u{bits}_end", "UInt64", [e for _, _, e in cs]))
out.append(reals("normal_f64", "Float64", normal, "CROSS_NORMAL"))
end64 = re.search(r"CROSS_NORMAL_END_POS = (\d+)u", normal).group(1)
out.append(f"comptime NORMAL_F64_END: UInt64 = {end64}\n")
out.append(reals("normal_f32", "Float32", normal, "CROSS_NORMALF"))
end32 = re.search(r"CROSS_NORMALF_END_POS = (\d+)u", normal).group(1)
out.append(f"comptime NORMAL_F32_END: UInt64 = {end32}")
print("\n".join(out))
