#!/usr/bin/env python3
"""Turn the spec's vectors.json into tests/vectors_data.mojo, so the tests need no JSON parser.

Usage: tools/gen_vectors.py path/to/vectors.json > tests/vectors_data.mojo
CI compares the output with the committed file.
"""
import json
import sys


def word4(ws):
    return "U4(" + ", ".join(f"0x{w}" for w in ws) + ")"


def lst(name, ty, items):
    return f"def {name}() -> List[{ty}]:\n    return [{', '.join(items)}]\n"


def main(path):
    v = json.load(open(path))
    out = ["# Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit.\n"]
    out.append("comptime U4 = SIMD[DType.uint32, 4]\n")
    out.append(f"comptime K: UInt32 = {v['K']}")
    out.append(f"comptime KEY = {word4(v['key'])}\n")

    t = v["T"]
    for field in ("o", "h", "o_out", "h_out"):
        out.append(lst(f"t_{field}", "U4", [word4(c[field]) for c in t]))

    f = v["F"]
    assert all(c["domain"] == "DOMAIN_STREAM" and c["aux"] == "AUX_STREAM" for c in f)
    out.append(lst("f_counter", "UInt64", [str(c["counter"]) for c in f]))
    out.append(lst("f_o", "U4", [word4(c["o"]) for c in f]))
    out.append(lst("f_h", "U4", [word4(c["h"]) for c in f]))

    s = v["stream_words"]
    out.append(lst("stream_first_word", "Int", [str(c["first_word"]) for c in s]))
    out.append(lst("stream_words", "U4", [word4(c["words"]) for c in s]))

    d = v["draws_from_position_0"]
    for name, ty in (("Float64", "Float64"), ("Float32", "Float32")):
        out.append(lst(f"{name.lower()}_index", "Int", list(d[name])))
        out.append(lst(f"{name.lower()}_value", ty, [repr(x) for x in d[name].values()]))
    out.append(lst("bool_index", "Int", list(d["Bool"])))
    out.append(lst("bool_value", "Bool", [str(bool(x)) for x in d["Bool"].values()]))

    k = v["derived_keys"]
    out.append(f"comptime SPLIT0 = {word4(k['split_child_0'])}")
    out.append(f"comptime SPLIT1 = {word4(k['split_child_1'])}")
    out.append(f"comptime FORK0 = {word4(k['fork_child_0_at_block_0'])}")
    out.append(f"comptime PURPOSE7 = {word4(k['purpose_7'])}\n")

    w = v["seed_whitening"]
    out.append(f"comptime SEED: UInt128 = {w['seed']}")
    out.append(f"comptime SEED_KEY = {word4(w['key'])}\n")
    out.append(lst("seed_f64_index", "Int", list(w["Float64"])))
    out.append(lst("seed_f64_value", "Float64", [repr(x) for x in w["Float64"].values()]))
    out.append(lst("seed_u32_index", "Int", list(w["UInt32"])))
    out.append(lst("seed_u32_value", "UInt32", [f"0x{x}" for x in w["UInt32"].values()]))
    print("\n".join(out).rstrip("\n"))


if __name__ == "__main__":
    main(sys.argv[1])
