#!/usr/bin/env python3
"""Mojo fixtures for tests/test_derived.mojo from tandem-c's cross-check headers and the tandem-cuda
fixtures that tandem-c carries.

    python3 tools/gen_derived.py ../tandem-c/tests > tests/derived_data.mojo
"""
import re
import sys

tests = sys.argv[1]


def read(name):
    with open(f"{tests}/{name}") as f:
        return f.read()


def cases(text, array, ints=True):
    # Entries are `{n, {values}, end_pos}`, with real values kept as their text.
    body = re.search(rf"{array}\[\] = \{{(.*?)\n\}};", text, re.S).group(1)
    out = []
    for n, vals, end in re.findall(r"\{(\d+)u(?:ll)?,\s*\{([^}]*)\},\s*(\d+)u\}", body):
        parts = [v.strip() for v in vals.split(",") if v.strip()]
        out.append((int(n), [int(v.rstrip("ul")) for v in parts] if ints else [v.rstrip("f") for v in parts], int(end)))
    return out


def fill_cases(text, array):
    # Entries are `{start, n, {values}, end_pos}`.
    body = re.search(rf"{array}\[\] = \{{(.*?)\n\}};", text, re.S).group(1)
    out = []
    for start, n, vals, end in re.findall(r"\{(\d+)ull,\s*(\d+)u(?:ll)?,\s*\{([^}]*)\},\s*(\d+)u\}", body):
        out.append((int(start), int(n), [int(v.strip().rstrip("ul")) for v in vals.split(",")], int(end)))
    return out


def ints(name, ty, values):
    return f"def {name}() -> List[{ty}]:\n    return [{', '.join(str(v) for v in values)}]\n"


def reals(name, ty, text, array):
    body = re.search(rf"{array}\[[^\]]*\] = \{{(.*?)\}};", text, re.S).group(1)
    values = [v.strip().rstrip("f") for v in body.split(",") if v.strip()]
    return f"def {name}() -> List[{ty}]:\n    return [{', '.join(values)}]\n"


below = read("cross_below.h")
fill = read("cross_fill_below.h")
normal = read("cross_normal.h")
exponential = read("cross_exponential.h")

out = ["# Generated by tools/gen_derived.py from tandem-c's cross-check headers. Do not edit.",
       "# Scalar cases start from `Tandem(42)` after one `next_bool`, fill cases from the key of seed 42",
       "# at the position `starts[i]`. The values of case i are",
       "# elements 64 * i to 64 * i + 63 of the `want` list.\n"]
for bits, array in [(32, "CROSS_U32"), (64, "CROSS_U64")]:
    cs = cases(below, array)
    assert all(len(v) == 64 for _, v, _ in cs)
    out.append(ints(f"below_u{bits}_bounds", f"UInt{bits}", [n for n, _, _ in cs]))
    out.append(ints(f"below_u{bits}_want", f"UInt{bits}", [x for _, v, _ in cs for x in v]))
    out.append(ints(f"below_u{bits}_end", "UInt64", [e for _, _, e in cs]))
for bits in (32, 64):
    cs = fill_cases(fill, f"CROSS_FILL_U{bits}")
    assert all(len(v) == 64 for _, _, v, _ in cs)
    out.append(ints(f"fill_below_u{bits}_starts", "UInt64", [st for st, _, _, _ in cs]))
    out.append(ints(f"fill_below_u{bits}_bounds", f"UInt{bits}", [n for _, n, _, _ in cs]))
    out.append(ints(f"fill_below_u{bits}_want", f"UInt{bits}", [x for _, _, v, _ in cs for x in v]))
    out.append(ints(f"fill_below_u{bits}_end", "UInt64", [e for _, _, _, e in cs]))
# Float64 normals: entries are `{start, {values}, end_pos}`, 64 ziggurat values from the key of
# seed 42.
rows = cases(normal, "CROSS_NORMAL", ints=False)
assert all(len(v) == 64 for _, v, _ in rows)
out.append(ints("normal_f64_starts", "UInt64", [st for st, _, _ in rows]))
out.append(f"def normal_f64_want() -> List[Float64]:\n    return [{', '.join(x for _, v, _ in rows for x in v)}]\n")
out.append(ints("normal_f64_end", "UInt64", [e for _, _, e in rows]))
out.append(reals("normal_f32", "Float32", normal, "CROSS_NORMALF"))
end32 = re.search(r"CROSS_NORMALF_END_POS = (\d+)u", normal).group(1)
out.append(f"comptime NORMAL_F32_END: UInt64 = {end32}")

# Exponentials: entries are `{start, {values}, end_pos}`, 64 values from the key of seed 42.
for bits, array, ty in ((64, "CROSS_EXPONENTIAL", "Float64"), (32, "CROSS_EXPONENTIALF", "Float32")):
    rows = cases(exponential, array, ints=False)
    assert all(len(v) == 64 for _, v, _ in rows)
    out.append(ints(f"exponential_f{bits}_starts", "UInt64", [st for st, _, _ in rows]))
    out.append(f"def exponential_f{bits}_want() -> List[{ty}]:\n    return [{', '.join(x for _, v, _ in rows for x in v)}]\n")
    out.append(ints(f"exponential_f{bits}_end", "UInt64", [e for _, _, e in rows]))

# tandem-cuda's fill fixtures, which tandem-c carries as cuda_fill_*.h: key of seed 42, K = 32.
cuda_below = read("cuda_fill_below.h")
cuda_normal = read("cuda_fill_normal.h")
for bits in (32, 64):
    body = re.search(rf"CROSS_BELOW{bits}\[\] = \{{(.*?)\n\}};", cuda_below, re.S).group(1)
    rows = re.findall(r"\{(\d+)u(?:ll)?,\s*(\d+),\s*\{([^}]*)\}\}", body)
    out.append(ints(f"cuda_below_u{bits}_range", f"UInt{bits}", [r[0] for r in rows]))
    out.append(ints(f"cuda_below_u{bits}_rejected", "Int", [r[1] for r in rows]))
    out.append(ints(f"cuda_below_u{bits}_want", f"UInt{bits}", [v.strip().rstrip("ul") for r in rows for v in r[2].split(",")]))
for bits, ty in ((64, "Float64"), (32, "Float32")):
    body = re.search(rf"CROSS_NORMAL{bits}\[\] = \{{(.*?)\n\}};", cuda_normal, re.S).group(1)
    rows = re.findall(r"\{(\d+)ull,\s*(\d+),\s*\{([^}]*)\}\}", body)
    out.append(ints(f"cuda_normal_f{bits}_pos", "UInt64", [r[0] for r in rows]))
    out.append(ints(f"cuda_normal_f{bits}_n", "Int", [r[1] for r in rows]))
    out.append(f"def cuda_normal_f{bits}_want() -> List[{ty}]:\n    return [{', '.join(v.strip().rstrip('f') for r in rows for v in r[2].split(','))}]\n")
print("\n".join(out).rstrip("\n"))
